project:
  type: book
  output-dir: _book

book:
  title: "EDI Dataset Preparation Guides"
  author: "Environmental Data Initiative and colleagues"
  description: "Community-developed guides for preparing and publishing datasets in the environmental sciences, and similar contexts, using the Ecological Metadata Language (EML)."
  date: "2022-05-25"
  favicon: edi-logo.png
  site-url: https://ediorg.github.io/dataset_preparation_guides
  repo-url: https://github.com/ediorg/dataset_preparation_guides
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    search: true
    logo: edi-logo.png
  chapters:
    - index.qmd
    - about.qmd

    - part: guide-eml-bp/preface.qmd
      chapters:
        - guide-eml-bp/chapter_01_introduction.qmd
        - guide-eml-bp/chapter_02_metadata_and_dataset_design_principles.qmd
        - guide-eml-bp/chapter_03_general_dataset_information.qmd
        - guide-eml-bp/chapter_04_people_and_organizations.qmd
        - guide-eml-bp/chapter_05_the_project_tree.qmd
        - guide-eml-bp/chapter_06_data_access_and_usage_rights.qmd
        - guide-eml-bp/chapter_07_keywords_coverage_and_annotations.qmd
        - guide-eml-bp/chapter_08_citations.qmd
        - guide-eml-bp/chapter_09_methods.qmd
        - guide-eml-bp/chapter_10_data_entities.qmd
        - guide-eml-bp/chapter_11_attributes_or_variable_descriptions.qmd
        - guide-eml-bp/chapter_12_additional_metadata.qmd
        - guide-eml-bp/appendix_1_specialized_elements.qmd
        - guide-eml-bp/appendix_2_XML_schemas_and_EML.qmd
        - guide-eml-bp/appendix_3_known_issues_and_gotchas.qmd

    - part: guide-special-cases/preface.qmd
      chapters: 
        - guide-special-cases/code.qmd
        - guide-special-cases/model-based.qmd
        - guide-special-cases/images-and-docs.qmd
        - guide-special-cases/spatial-data.qmd
        - guide-special-cases/moving-platforms.qmd
        - guide-special-cases/other-repositories.qmd
        - guide-special-cases/large-offline.qmd

    - part: guide-domain-specific/preface.qmd
      chapters:
        - guide-domain-specific/ecocom.qmd
        - guide-domain-specific/hymet.qmd
        - guide-domain-specific/soil-carbon.qmd
    - references.qmd

execute:
  freeze: auto

bibliography: references.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrreprt



