project:
  type: book
  output-dir: _book

book:
  title: "Data Package Best Practices"
  author: "Environmental Data Initiative"
  description: "Best practice recommendations for data packages, described by Ecological Metadata Language (EML). 2022-05-25 version"
  date: "`r Sys.Date()`"
  favicon: edi-logo.png
  site-url: https://ediorg.github.io/dataset_preparation_guides
  repo-url: https://github.com/ediorg/dataset_preparation_guides
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - about.qmd
    - guide-eml-bp/eml-best-practices.qmd
    - guide-special-cases/dataset-design-special-cases.qmd
    - guide-domain-specific/scientific-domain.qmd
    - references.qmd

execute:
  freeze: auto

bibliography: references.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrreprt



