# Overview {.unnumbered}

This website contains current \"Best Practice\" recommendations for ecological and environmental science data packages. These recommendations are directed towards the following goals:

- Minimize heterogeneity of EML-described data packages to simplify development and re-use of software
- Maximize interoperability to facilitate data synthesis
- Provide guidance and clarification on
  - the use of Ecological Metadata Language (EML)
  - design a data package
  - prepare a data product for synthesis

To participate in the "Best Practices for Data Packages" project, see "[About this site](about.qmd)".

This site is rendered as a Quarto book. To learn more about Quarto books visit <https://quarto.org/docs/books>.

## Book sections

### [EML Metadata Concepts](guide-eml-bp/eml-best-practices.qmd)
The recommendations for EML metadata apply to all data packages. This section subsumes V3 of the static PDF document "Best Practices for Dataset Metadata in Ecological Metadata Language (EML)," last updated in 2017. The entire most recent (versioned, citable) release will be made available as a PDF. 

 **[Best Practices for Dataset Metadata in Ecological Metadata Language (EML)](guide-eml-bp/eml-best-practices.qmd)**
  
### [Data Package Design](guide-special-cases/dataset-design-special-cases.qmd)
Considerations for a well designed data package including special cases based on data type, format, or acquisition method. Examples are images, documents, raw data stored in other repositories. 

**[Recommendations for data package design](guide-special-cases/dataset-design-special-cases.qmd)**

### [Data Products for Synthesis Research](guide-domain-specific/scientific-domain.qmd)
Recommendations for community developed data products. The data packages are derived from raw data and reformatted to meet certain data harmonization standards. Many of these data products have extensive related code bases, which recommendations can take into account and link to. 

**[Recommendations for data products from specific scientific domains](guide-domain-specific/scientific-domain.qmd)**